version: "3"

# docker-compose up -d

services:
  centos:
    build: ./
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  mysql:
    image: mariadb:latest
    volumes:
       - ./mysqldumps:/docker-entrypoint-initdb.d
    ports:
       - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=zaq12wsx
      - MYSQL_USER=pentaho
      - MYSQL_PASSWORD=zaq12wsx
      - TZ=America/New_York
