version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/#running-pi-hole-docker
# https://hub.docker.com/r/pihole/pihole/ and https://docs.pi-hole.net/

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
# We are not running DHCP
#      - "67:67/udp"
      - "9080:80/tcp"
      - "9443:443/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'XXXXXXXXXX'
# Default DNS is localhost for home network, google (8.8.8.8), cloudflare (1.1.1.1)
      PIHOLE_DNS_: '127.0.0.1;8.8.8.8;1.1.1.1'
      FTLCONF_REPLY_ADDR4: '192.168.0.4'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
# Set DNS servers. Note 127.0.0.1 is necessary
# These can also be set via ENV vars or directly on the PiHole settings > DNS tab
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
# Recommended but not required (DHCP needs NET_ADMIN)
#   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN
    restart: unless-stopped
