version: "3"

# docker-compose up -d

services:
    php:
        #        image: php:apache
        build: ./
        ports:
            - 8081:80
        volumes:
            - ./html:/var/www/html
    mysql:
        image: mariadb:latest
        volumes:
            - ./mysqldumps:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=zaq12wsx
            - TZ=America/New_York
