version: "2"

# See https://hub.docker.com/r/jacobalberty/unifi/

services:
  unify:
    container_name: unifi
    image: jacobalberty/unifi:latest
    ports:
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
      - "8880:8880/tcp"
      - "6789:6789/tcp"
      - "3478:3478/udp"
      - "10001:10001/udp"
    environment:
      TZ: 'America/New_York'
      RUNAS_UID0: "false"
    volumes:
      - './unifi/:/unifi/'
    restart: unless-stopped
